import os

DIR_PATH = os.path.dirname(os.path.realpath(__file__)) + "/data"
GREETING_FILE = DIR_PATH + "/greeting"
ORTHER_FILE = DIR_PATH + "/orther"
WH_WEATHER_FILE = DIR_PATH + "/wh_weather"
YESNO_WEATHER_FILE = DIR_PATH + "/yesno_weather"
DIC_WEATHER_FILE = DIR_PATH + "/dic_weather"
TRAIN_GREETING_FILE = DIR_PATH + "/train_greeting"
RAW_TRAIN_NER_FILE = DIR_PATH + "/raw_train_ner"
TRAIN_NER_FILE = DIR_PATH + "/train_ner"
MODEL_NER_FILE = DIR_PATH + "/chatbot-ner.ser.gz"
GREETING_TRAIN_FILE = DIR_PATH + "/greeting_train_file"
GREETING_MODEL = DIR_PATH + "/model.greeting.pkl"
INTEND_VECTORIZER_MODEL = DIR_PATH + "/model.vectorzier.intend.pkl"
INTEND_CLASSIFY_MODEL = DIR_PATH + "/model.classify.intend.pkl"